### ISSUE TITLE
ERR_CONNECTION_REFSED {SIGN_UP}

### ISSUE THREAD

**Issue by cosmicgz** [ujjwalnp/coreq-backend#11]
![image](https://github.com/ujjwalnp/coreq-backend/assets/90420230/37a64cf4-3555-4032-b271-a0db0607c9df)

**Comment by ujjwalnp** [comment]
This problem is encountering because you haven't defined mongodb connection URI string which must be defined on environment variables.
In the project's server directory create `.env` file which must be the following format:
```
MONGO_URL = 'your-connection-string'
JWT_SECRET = 'your-JWT-SECRET'
SERVER_PORT = 'PORT'
```
